// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA1JWLggD7NULh15r1_9Ewe09r5DTJ3fCE',
    appId: '1:1025385511240:web:7f5456021a66ff54565b7d',
    messagingSenderId: '1025385511240',
    projectId: 'west-bank-az-gsk',
    authDomain: 'west-bank-az-gsk.firebaseapp.com',
    storageBucket: 'west-bank-az-gsk.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCdon2fcrBe_H7JV6WbpiueOWFbJV8wuRY',
    appId: '1:1025385511240:android:807e09f21d3c5dcd565b7d',
    messagingSenderId: '1025385511240',
    projectId: 'west-bank-az-gsk',
    storageBucket: 'west-bank-az-gsk.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAXG4gnN4pJfR5Ikc5jceCqClmMB7fUctU',
    appId: '1:1025385511240:ios:010060f1d0989693565b7d',
    messagingSenderId: '1025385511240',
    projectId: 'west-bank-az-gsk',
    storageBucket: 'west-bank-az-gsk.appspot.com',
    iosClientId:
        '1025385511240-7a5vo7du0pt15anv84g60ekshvb7uvur.apps.googleusercontent.com',
    iosBundleId: 'com.example.bustracker',
  );
}
